### ISSUE TITLE
App update for Homey Pro 2023?

### ISSUE THREAD

**Issue by dcj-jorissen** [gruijter/PW2PY_DOCKER#1]
Hello Robin, were you planning an update for this new Homey Pro?![image](https://user-images.githubusercontent.com/79135404/195776529-514e512a-5308-4576-a75b-e0c5f9faef2c.png)

**Comment by gruijter** [comment]
https://community.homey.app/t/plugwise2py-monitor-and-control-plugwise-circles-without-stretch/10635/22
